name: posting-by-issue

on:
  issues:
    types:
      - labeled

jobs:
  posting-release:
    if: github.event.label.name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release post
        uses: ./
        with:
          post_base_path: '_posts'
          # author: 'author'
          # author_email: 'author@noreply.com'
